### PR TITLE
Update links to ggplot function and PMC citation

### PR DESCRIPTION
**Pull request by ycl6**
The PR addresses the bug reported in #82 that is causing the package to be archived by CRAN.

This updates the cross referencing to the `ggplot` function in the `ggplot2` package, also, I updated the PMC link to the Enrichr paper at the same time.

### CODE REVIEW

**Comment by ycl6** [comment]
Hi @wjawaid Thanks for checking in and merging all the PRs👍 
I plan to give the newly updated package in the master branch a full test later in the year and possibly update the vignettes when required.

**Comment by tagtag** [comment]
Is it possible for you to tell me when it is planned to submit to CRAN? I am using enrichR in my bioconductor package, TDbasedUFEadv, and Biocouductor forces me to remove it from my package.....

**Comment by wjawaid** [comment]
Hi. Thank you very much for your contributions. I plan to submit it again
around 15 December. I just want to check it is working properly.

**Comment by mihem** [comment]
@wjawaid any plans to still fix this? would be great to have enrichR on CRAN again

**Pull request merged**
